// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$0 from "./routes/_app.tsx";
import * as $$$$$$$$0 from "./sections/YTFeed.tsx";
import * as $$$$$$$$1 from "./sections/LinkTree.tsx";
import * as $$$$$$$$$$$$$0 from "./apps/eva.ts";
import { DecoManifest } from "$live/types.ts";

const manifest = {
  "routes": {
    "./routes/_app.tsx": $$$$0,
  },
  "sections": {
    "deco-sites/forrageira/sections/LinkTree.tsx": $$$$$$$$1,
    "deco-sites/forrageira/sections/YTFeed.tsx": $$$$$$$$0,
  },
  "apps": {
    "deco-sites/forrageira/apps/eva.ts": $$$$$$$$$$$$$0,
  },
  "name": "deco-sites/forrageira",
  "islands": {},
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest satisfies DecoManifest;
