// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/LinkTree.tsx";
import * as $$$$$$1 from "./sections/YTFeed.tsx";

const manifest = {
  "sections": {
    "deco-sites/forrageira/sections/LinkTree.tsx": $$$$$$0,
    "deco-sites/forrageira/sections/YTFeed.tsx": $$$$$$1,
  },
  "apps": {
    "deco-sites/forrageira/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/forrageira",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
